### ISSUE TITLE
Password are not Hashed

### ISSUE THREAD

**Issue by Velocity23** [Sam-Neale/VACenter#1]
You should be hashing the passwords. Nobody should be able to see them, not even admins.

**Comment by Sam-Neale** [comment]
It is intentional that admins can see this with a little bit of struggle.

**Comment by Velocity23** [comment]
**No.** No, no, no and _**no**_. Nobody should **EVER** be able to view their users' passwords. People reuse passwords on multiple sites, that's just a fact, and BA CEOs abusing their power does happen. It's a dangerous combination. Furthermore, say a hacker got into the server - then they would have access to everyone's passwords which is definitely something you do not want.

**Comment by Sam-Neale** [comment]
Working on

**Comment by Sam-Neale** [comment]
This issue has now been resolved see commit 9263a7ae2f1a64ba834f33ab8231f8f3092852c7 and Pull Request #5
