### ISSUE TITLE
Ranks should be calculated On-the-Fly

### ISSUE THREAD

**Issue by Velocity23** [Sam-Neale/VACenter#2]
Currently someone could alter their rank by forging a socket request, but if the rank is calculated dynamically every time it is needed then this will not be an issue.

**Comment by Sam-Neale** [comment]
Feedback taken, will implement when I finish the account page system

**Comment by Sam-Neale** [comment]
Working on it

**Comment by Sam-Neale** [comment]
Auto ranks made see Commit a06548f8f7c6a6ba798c927ccdf309bce0720116
