### ISSUE TITLE
Comment box on PIREP page

### ISSUE THREAD

**Issue by xvalespx** [Sam-Neale/VACenter#21]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
A comment box where pilots can add some notes about the flight they did. 

**Describe alternatives you've considered**
..

**Additional context**
..

**Comment by Sam-Neale** [comment]
Feature, added to Alitalia Virtual CC, will add to git when needed, required removal of all current PIREPS
